<?php
/**
 * Generated by Protobuf protoc plugin.
 */


namespace ProtobufTest\Protos;

/**
 * Protobuf message : AddressBook
 *
 * @\Protobuf\Annotation\Descriptor(
 *   name="AddressBook",
 *   package="ProtobufTest.Protos",
 *   fields={
 *     @\Protobuf\Annotation\Field(
 *       name="person",
 *       tag=1,
 *       type=11,
 *       label=3,
 *       reference="ProtobufTest.Protos.Person"
 *     )
 *   }
 * )
 */
class AddressBook extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * person repeated message = 1
     *
     * @var \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Person">
     */
    protected $person = null;

    /**
     * Check if 'person' has a value
     *
     * @return bool
     */
    public function hasPersonList()
    {
        return $this->person !== null;
    }

    /**
     * Get 'person' value
     *
     * @return \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Person">
     */
    public function getPersonList()
    {
        return $this->person;
    }

    /**
     * Set 'person' value
     *
     * @param \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Person"> $value
     */
    public function setPersonList(\Doctrine\Common\Collections\Collection $value)
    {
        return $this->person = $value;
    }

    /**
     * Add a new element to 'person'
     *
     * @param \ProtobufTest\Protos\Person $value
     */
    public function addPerson(\ProtobufTest\Protos\Person $value)
    {
        $this->person[] = $value;
    }

    /**
     * Get unknown values
     *
     * @return Protobuf\UnknownFieldSet
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->person !== null) {
            foreach ($this->person as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \ProtobufTest\Protos\Person();

                if ($this->person === null) {
                    $this->person = new \Protobuf\MessageCollection();
                }

                $this->person->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->person !== null) {
            foreach ($this->person as $val) {
                $writer->writeVarint($stream, 10);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = new \Protobuf\ReadContext($stream, $config->getStreamReader());
        $message = new \ProtobufTest\Protos\AddressBook();

        $message->readFrom($context);

        return $message;
    }


}

