<?php
/**
 * Generated by Protobuf protoc plugin.
 */


namespace ProtobufTest\Protos;

/**
 * Protobuf message : Complex
 *
 * @\Protobuf\Annotation\Descriptor(
 *   name="Complex",
 *   package="ProtobufTest.Protos",
 *   fields={
 *     @\Protobuf\Annotation\Field(
 *       name="enum",
 *       tag=1,
 *       type=14,
 *       label=1,
 *       reference="ProtobufTest.Protos.Complex.Enum"
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="nested",
 *       tag=2,
 *       type=11,
 *       label=1,
 *       reference="ProtobufTest.Protos.Complex.Nested"
 *     )
 *   }
 * )
 */
class Complex extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * enum optional enum = 1
     *
     * @var \ProtobufTest\Protos\Complex\Enum
     */
    protected $enum = null;

    /**
     * nested optional message = 2
     *
     * @var \ProtobufTest\Protos\Complex\Nested
     */
    protected $nested = null;

    /**
     * Check if 'enum' has a value
     *
     * @return bool
     */
    public function hasEnum()
    {
        return $this->enum !== null;
    }

    /**
     * Get 'enum' value
     *
     * @return \ProtobufTest\Protos\Complex\Enum
     */
    public function getEnum()
    {
        return $this->enum;
    }

    /**
     * Set 'enum' value
     *
     * @param \ProtobufTest\Protos\Complex\Enum $value
     */
    public function setEnum(\ProtobufTest\Protos\Complex\Enum $value)
    {
        return $this->enum = $value;
    }

    /**
     * Check if 'nested' has a value
     *
     * @return bool
     */
    public function hasNested()
    {
        return $this->nested !== null;
    }

    /**
     * Get 'nested' value
     *
     * @return \ProtobufTest\Protos\Complex\Nested
     */
    public function getNested()
    {
        return $this->nested;
    }

    /**
     * Set 'nested' value
     *
     * @param \ProtobufTest\Protos\Complex\Nested $value
     */
    public function setNested(\ProtobufTest\Protos\Complex\Nested $value)
    {
        return $this->nested = $value;
    }

    /**
     * Get unknown values
     *
     * @return Protobuf\UnknownFieldSet
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->enum !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->enum->value());
        }

        if ($this->nested !== null) {
            $innerSize = $this->nested->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                $this->enum = \ProtobufTest\Protos\Complex\Enum::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                $innerSize  = $reader->readVarint($stream);
                $innerMessage = new \ProtobufTest\Protos\Complex\Nested();

                $this->nested = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->enum !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->enum->value());
        }

        if ($this->nested !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeVarint($stream, $this->nested->serializedSize($sizeContext));
            $this->nested->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = new \Protobuf\ReadContext($stream, $config->getStreamReader());
        $message = new \ProtobufTest\Protos\Complex();

        $message->readFrom($context);

        return $message;
    }


}

