<?php
/**
 * Generated by Protobuf protoc plugin.
 */


namespace ProtobufTest\Protos;

/**
 * Protobuf message : Repeated
 *
 * @\Protobuf\Annotation\Descriptor(
 *   name="Repeated",
 *   package="ProtobufTest.Protos",
 *   fields={
 *     @\Protobuf\Annotation\Field(
 *       name="string",
 *       tag=1,
 *       type=9,
 *       label=3
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="int",
 *       tag=2,
 *       type=5,
 *       label=3
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="nested",
 *       tag=3,
 *       type=11,
 *       label=3,
 *       reference="ProtobufTest.Protos.Repeated.Nested"
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="packed",
 *       tag=4,
 *       type=5,
 *       label=3,
 *       pack=true
 *     )
 *   }
 * )
 */
class Repeated extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * string repeated string = 1
     *
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $string = null;

    /**
     * int repeated int32 = 2
     *
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $int = null;

    /**
     * nested repeated message = 3
     *
     * @var \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Repeated\Nested">
     */
    protected $nested = null;

    /**
     * packed repeated int32 = 4
     *
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $packed = null;

    /**
     * Check if 'string' has a value
     *
     * @return bool
     */
    public function hasStringList()
    {
        return $this->string !== null;
    }

    /**
     * Get 'string' value
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStringList()
    {
        return $this->string;
    }

    /**
     * Set 'string' value
     *
     * @param \Doctrine\Common\Collections\Collection $value
     */
    public function setStringList(\Doctrine\Common\Collections\Collection $value)
    {
        return $this->string = $value;
    }

    /**
     * Add a new element to 'string'
     *
     * @param string $value
     */
    public function addString($value)
    {
        $this->string[] = $value;
    }

    /**
     * Check if 'int' has a value
     *
     * @return bool
     */
    public function hasIntList()
    {
        return $this->int !== null;
    }

    /**
     * Get 'int' value
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getIntList()
    {
        return $this->int;
    }

    /**
     * Set 'int' value
     *
     * @param \Doctrine\Common\Collections\Collection $value
     */
    public function setIntList(\Doctrine\Common\Collections\Collection $value)
    {
        return $this->int = $value;
    }

    /**
     * Add a new element to 'int'
     *
     * @param int $value
     */
    public function addInt($value)
    {
        $this->int[] = $value;
    }

    /**
     * Check if 'nested' has a value
     *
     * @return bool
     */
    public function hasNestedList()
    {
        return $this->nested !== null;
    }

    /**
     * Get 'nested' value
     *
     * @return \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Repeated\Nested">
     */
    public function getNestedList()
    {
        return $this->nested;
    }

    /**
     * Set 'nested' value
     *
     * @param \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Repeated\Nested"> $value
     */
    public function setNestedList(\Doctrine\Common\Collections\Collection $value)
    {
        return $this->nested = $value;
    }

    /**
     * Add a new element to 'nested'
     *
     * @param \ProtobufTest\Protos\Repeated\Nested $value
     */
    public function addNested(\ProtobufTest\Protos\Repeated\Nested $value)
    {
        $this->nested[] = $value;
    }

    /**
     * Check if 'packed' has a value
     *
     * @return bool
     */
    public function hasPackedList()
    {
        return $this->packed !== null;
    }

    /**
     * Get 'packed' value
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPackedList()
    {
        return $this->packed;
    }

    /**
     * Set 'packed' value
     *
     * @param \Doctrine\Common\Collections\Collection $value
     */
    public function setPackedList(\Doctrine\Common\Collections\Collection $value)
    {
        return $this->packed = $value;
    }

    /**
     * Add a new element to 'packed'
     *
     * @param int $value
     */
    public function addPacked($value)
    {
        $this->packed[] = $value;
    }

    /**
     * Get unknown values
     *
     * @return Protobuf\UnknownFieldSet
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->string !== null) {
            foreach ($this->string as $val) {
                $size += 1;
                $size += $calculator->computeStringSize($val);
            }
        }

        if ($this->int !== null) {
            foreach ($this->int as $val) {
                $size += 1;
                $size += $calculator->computeVarintSize($val);
            }
        }

        if ($this->nested !== null) {
            foreach ($this->nested as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->packed !== null) {
            $innerSize = 0;

            foreach ($this->packed as $val) {
                $innerSize += $calculator->computeVarintSize($val);
            }

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {

                if ($this->string === null) {
                    $this->string = new \Protobuf\ScalarCollection();
                }

                $this->string->add($reader->readString($stream));

                continue;
            }

            if ($tag === 2) {

                if ($this->int === null) {
                    $this->int = new \Protobuf\ScalarCollection();
                }

                $this->int->add($reader->readVarint($stream));

                continue;
            }

            if ($tag === 3) {
                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \ProtobufTest\Protos\Repeated\Nested();

                if ($this->nested === null) {
                    $this->nested = new \Protobuf\MessageCollection();
                }

                $this->nested->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 4) {
                $innerSize  = $reader->readVarint($stream);
                $innerLimit = $stream->tell() + $innerSize;

                if ($this->packed === null) {
                    $this->packed = new \Protobuf\ScalarCollection();
                }

                while ($stream->tell() < $innerLimit) {
                    $this->packed->add($reader->readVarint($stream));
                }

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->string !== null) {
            foreach ($this->string as $val) {
                $writer->writeVarint($stream, 10);
                $writer->writeString($stream, $val);
            }
        }

        if ($this->int !== null) {
            foreach ($this->int as $val) {
                $writer->writeVarint($stream, 16);
                $writer->writeVarint($stream, $val);
            }
        }

        if ($this->nested !== null) {
            foreach ($this->nested as $val) {
                $writer->writeVarint($stream, 26);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->packed !== null) {
            $innerSize   = 0;
            $calculator  = $sizeContext->getSizeCalculator();

            foreach ($this->packed as $val) {
                $innerSize += $calculator->computeVarintSize($val);
            }

            $writer->writeVarint($stream, 34);
            $writer->writeVarint($stream, $innerSize);

            foreach ($this->packed as $val) {
                $writer->writeVarint($stream, $val);
            }
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = new \Protobuf\ReadContext($stream, $config->getStreamReader());
        $message = new \ProtobufTest\Protos\Repeated();

        $message->readFrom($context);

        return $message;
    }


}

